apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.destination.repo}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - springboot
    - microservice
    - mvc
    
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  providesApis:
    - CustomerManagement
    - ProductManagement
    - OrderManagement
    - PaymentManagement
    - DeliveryManagement
    - E-Commerce-MVC
  
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: CustomerManagement
  description: ${{ values.description }}
  links:
    - url: http://localhost:9901/swagger-ui.html
      title: CustomerManagement Website
      icon: dashboard
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.destination.owner}}
  apiConsumedBy:
    - OrderManagement
  definition:
    $text: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}/blob/master/CustomerManagement/src/main/resources/api-docs.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: DeliveryManagement
  description: ${{ values.description }}
  links:
    - url: http://localhost:9901/swagger-ui.html
      title: DeliveryManagement Website
      icon: dashboard
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.destination.owner}}
  definition:
    $text: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}/blob/master/DeliveryManagement/src/main/resources/api-docs.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: E-Commerce-MVC
  description: ${{ values.description }}
  links:
    - url: http://localhost:4041/mvcec/shop
      title: E-Commerce-MVC Website
      icon: dashboard
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.destination.owner}}
  definition:
    $text: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}/blob/master/E-Commerce-MVC/src/main/resources/api-docs.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ProductManagement
  description: ${{ values.description }}
  links:
    - url: http://localhost:9904/swagger-ui.html
      title: ProductManagement Website
      icon: dashboard
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.destination.owner}}
  apiConsumedBy:
    - OrderManagement
  definition:
    $text: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}/blob/master/ProductManagement/src/main/resources/api-docs.yaml

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: OrderManagement
  description: ${{ values.description }}
  links:
    - url: http://localhost:9903/swagger-ui.html
      title: OrderManagement Website
      icon: dashboard
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.destination.owner}}
  apiConsumedBy:
    - PaymentManagement
  consumesApis:
    - CustomerManagement
    - ProductManagement
  definition:
    $text: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}/blob/master/OrderManagement/src/main/resources/api-docs.yaml

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: PaymentManagement
  description: ${{ values.description }}
  links:
    - url: http://localhost:9905/swagger-ui.html
      title: PaymentManagement Website
      icon: dashboard
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.destination.owner}}
  consumesApis:
    - OrderManagement
  definition:
    $text: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}/blob/master/PaymentManagement/src/main/resources/api-docs.yaml
