openapi: 3.0.3
info:
  title: My Spring REST API
  version: 1.0.0
servers:
  - url: http://localhost:9901
paths:
  /users/status:
    get:
      summary: Retrieve status
      operationId: getStatus
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
